easy_admin:
    entities:
        Project:
            class: Odiseo\Bundle\AppBundle\Entity\Project
            label: 'Blog'
            image_base_path: '/media/images/'
            form:
                fields:
                  - { property: 'name', label: 'Nombre' }
                  - { property: 'description', label: 'Descripción', type: 'ckeditor' }
                  - { property: 'imageFile', label: 'Image', type: 'file' }
            list:
                title: '%%entity_label%%'
                fields:
                    - 'id'
                    - { property: 'name', label: 'Nombre' }
                    - { property: 'imageName', label: 'Imagen', type: 'image' }
                    - { property: 'createdAt', label: 'Fecha creación' }
            edit:
                title:  'Editar noticia %%entity_id%%'
            new:
                title:  'Crear nueva noticia'
            show:
                title:  'Noticia %%entity_id%%'
                fields:
                    - 'id'
                    - { property: 'name', label: 'Nombre' }
                    - { property: 'description', type: 'raw' }
                    - { property: 'imageName', label: 'Image', type: 'image' }
                    - 'createdAt'