odiseo_backend:
    resource: "@OdiseoBackendBundle/Resources/config/routing/main.yml"
    prefix:   /

odiseo_app_backend_dashboard:
    pattern: /dashboard
    defaults: { _controller: "OdiseoAppBundle:Backend/Main:dashboard" }