odiseo_app_frontend_homepage:
    path:     /
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:index" }

odiseo_app_frontend_about:
    path:     /about
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:about" }

odiseo_app_frontend_blog:
    path:     /blog
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:blog" }

odiseo_app_frontend_contact:
    path:     /contact
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:contact" }

odiseo_app_frontend_contact_send:
    path:     /contact/send
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:contactSend" }