odiseo_app_frontend_homepage:
    path:     /
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:index" }

odiseo_app_frontend_about:
    path:     /beraca{page}
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:about", page:1 }
    requirements:
      _method:  GET
      page: \d+


odiseo_app_frontend_news:
    path:     /novedades{page}
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:news" , page:1 }
    requirements:
      _method:  GET
      page: \d+

odiseo_app_frontend_contact:
    path:     /contacto
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:contact" }

odiseo_app_frontend_contact_send:
    path:     /contact/send
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:contactSend" }