odiseo_app_frontend_homepage:
    path:     /
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:index" }

odiseo_app_frontend_about:
    path:     /beraca
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:about" }

odiseo_app_frontend_news:
    path:     /novedades
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:news" }

odiseo_app_frontend_contact:
    path:     /contacto
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:contact" }

odiseo_app_frontend_contact_send:
    path:     /contact/send
    defaults: { _controller: "OdiseoAppBundle:Frontend/Home:contactSend" }