Odiseo\Bundle\AppBundle\Entity\Beraca:
    type: entity
    table: odiseo_beraca
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
        description:
            column: description
            type: text
            nullable: true
        imageName:
            type: string
            length: 255
            nullable: true
        createdAt:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update