Odiseo\Bundle\AppBundle\Entity\HomeImage:
    type: entity
    table: odiseo_home_image
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        imageName:
            column: image_name
            type: string
        createdAt:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        homeConfiguration:
          targetEntity: Odiseo\Bundle\AppBundle\Entity\HomeConfiguration
          inversedBy: images
          joinColumn:
            name: homeConfiguration_id
            referencedColumnName: id
            onDelete: CASCADE