Odiseo\Bundle\AppBundle\Entity\HomeConfiguration:
    type: entity
    table: odiseo_home_configuration
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        images:
          targetEntity: Odiseo\Bundle\AppBundle\Entity\HomeImage
          mappedBy: homeConfiguration
          cascade: ["persist", "merge"]