Odiseo\Bundle\AppBundle\Entity\ProjectImage:
    type: entity
    table: odiseo_project_image
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
        imageName:
            column: image_name
            type: string
        isMain:
            column: is_main
            type: boolean
            options:
                default: false
        createdAt:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        homeConfiguration:
          targetEntity: Odiseo\Bundle\AppBundle\Entity\HomeConfiguration
          inversedBy: images
          joinColumn:
            name: homeConfiguration_id
            referencedColumnName: id
            onDelete: CASCADE