Odiseo\Bundle\AppBundle\Entity\ProjectFile:
    type: entity
    table: odiseo_project_file
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
        fileName:
            column: file_name
            type: string
        position:
            column: position
            type: integer
            options:
                default: 0
        createdAt:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        project:
          targetEntity: Odiseo\Bundle\AppBundle\Entity\Project
          inversedBy: files
          joinColumn:
            name: project_id
            referencedColumnName: id
            onDelete: CASCADE