fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Odiseo\Bundle\AppBundle\Entity\User

fos_js_routing:
    routes_to_expose: [ 'odiseo_app_frontend_contact_send' ]

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        image_adapter:
            local:
                directory: %kernel.root_dir%/../web/media/images
                create:    true
        file_adapter:
            local:
                directory: %kernel.root_dir%/../web/media/files
                create: true
    filesystems:
        images_fs:
            adapter:   image_adapter
        files_fs:
            adapter:   file_adapter

vich_uploader:
   db_driver: orm # or mongodb or propel or phpcr
   storage:   gaufrette
   mappings:
        images:
            uri_prefix:         /images
            upload_destination: images_fs
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        files:
            uri_prefix:         /files
            upload_destination: files_fs
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/media/images
    filter_sets:
        cache: ~
        project_list:
            filters:
                thumbnail: { size: [710, 513], mode: outbound }
        project_gallery:
            filters:
                thumbnail: { size: [900, 600], mode: outbound }

beelab_tag:
    tag_class: Odiseo\Bundle\AppBundle\Entity\Tag

sylius_resource:
    resources:
        odiseo.user:
            driver: doctrine/orm
            classes:
                model: Odiseo\Bundle\AppBundle\Entity\User
                repository: Odiseo\Bundle\AppBundle\Repository\UserRepository

        odiseo.project:
            driver: doctrine/orm
            classes:
                model: Odiseo\Bundle\AppBundle\Entity\Project
                repository: Odiseo\Bundle\AppBundle\Repository\ProjectRepository
        odiseo.tag:
            driver: doctrine/orm
            classes:
                model: Odiseo\Bundle\AppBundle\Entity\Tag
